config/routes.rb
Rails.application.routes.draw do
  resources :packs do
    resources :levels

    member do
      get :download
    end
  end

  resources :workflows do
    collection do
      get :show_welcome
      get :show_rules
      get :show_controls

      get :show_facebook_page
      get :show_twitter_page
      get :show_invite_friends
      get :show_random_level
      get :show_donation

      post :show_next_level
    end
  end

  resources :scores

  resources :users do
    member do
      get  :popular_friends
      get  :is_like_facebook_page      # question
      get  :custom_invitation          # JSON with data for custom user invitation
      post :update_send_invitations_at # user just invited some friends
      get  :unsubscribe_from_mailing   # remove user from mailing list (remove from madmimi)

      get  :latest_levels
      get  :levels_to_solve
      get  :scores_to_improve
    end
  end

  # API

  namespace :api do
    resources :levels do
      collection do
        get :random
      end
    end
  end

  get '/rankings',        :to => 'users#index', :type => 'global',  :as => :rankings
  get '/friends_ranking', :to => 'users#index', :type => 'friends', :as => :friends_ranking

  # Root
  root :to => "packs#show", :id => 'dimitri-yorick' # or 'Novoban'
  post "/" => "packs#show", :id => 'dimitri-yorick'

  # Redirect user back to the page before login
  # http://forrst.com/posts/Redirect_a_user_back_to_the_current_page_after_a-R1q
  get '/connect_facebook',          :to => 'sessions#connect_facebook'

  # OmniAuth (facebook)
  match '/auth/:provider/callback', :to => 'sessions#create',  via: [:get, :post]
  match '/auth/failure',            :to => 'sessions#failure', via: [:get, :post]
  get   '/login',                   :to => 'sessions#new'
  get   '/logout',                  :to => 'sessions#destroy', :as => :logout

  get   '/banner',                  :to => 'pages#banner'
  get   '/privacy_policy',          :to => 'pages#privacy_policy'
  get   '/terms_of_service',        :to => 'pages#terms_of_service'
  get   '/stats',                   :to => 'pages#stats'
  get   '/master_thesis',           :to => 'pages#master_thesis'
end

app/models/user.rb
require 'net/https'

class User < ApplicationRecord
  extend FriendlyId

  friendly_id :name, :use => :slugged

  # Constants

  DAYS_BEFORE_UPDATING_FRIENDS        = 5
  DAYS_WITHOUT_ADS_IF_FRIENDS_INVITED = 7
  DAYS_WITHOUT_FRIENDS_INVITE_POPUP   = 7

  # Associations
  has_many :user_user_links,
           :primary_key => :f_id

  has_many :friends,
           :through => :user_user_links

  has_many :scores,
           :class_name => 'LevelUserLink'

  has_many :best_scores,
           -> { where(:best_level_user_score => true) },
           :class_name => 'LevelUserLink'

  has_many :levels,
           :through => :scores

  has_many :pack_user_links

  # Nested attributes

  # Validations
  validates :f_id, :uniqueness => true

  # Callbacks

  # Scopes

  def self.registered
    where('email IS NOT NULL')
  end

  def self.not_registered
    where('email IS NULL')
  end

  # Methods

  def self.update_or_create(credentials)
    token = credentials['token']
    graph = Koala::Facebook::API.new(token)
    profile = graph.get_object('me')

    # raise [credentials.inspect, profile.inspect, credentials['expires_at'], token.inspect].inspect

    # Debug
    File.open("tmp/#{profile['id']}-#{Time.now.day}-#{Time.now.month}-#{Time.now.year}.yml", "w") do |file|
      file.write profile.to_yaml
    end

    # Admin get an extended token for the fan page publications
    if profile['id'] == ENV['FACEBOOK_ADMIN_ID']
      new_token = extended_token(token)

      if new_token.present?
        expires_at = Time.now.to_datetime + 60.days
        token = new_token
      else
        expires_at = credentials['expires'] ? Time.at(credentials['expires_at']).to_datetime : Time.now.to_datetime + 10.year
      end
    else
      expires_at = credentials['expires'] ? Time.at(credentials['expires_at']).to_datetime : Time.now.to_datetime + 10.year
    end

    # Hash with user values
    user_hash = {
      :name           => profile['name'],
      :email          => profile['email'],
      :picture        => graph.get_picture('me'),
      :gender         => profile['gender'],
      :locale         => profile['locale'],
      :f_id           => profile['id'],
      :f_token        => token,
      :f_first_name   => profile['first_name'],
      :f_middle_name  => profile['middle_name'],
      :f_last_name    => profile['last_name'],
      :f_username     => profile['username'],
      :f_link         => profile['link'],
      :f_timezone     => profile['timezone'],
      :f_updated_time => profile['updated_time'],
      :f_verified     => profile['verified'],
      :f_expires      => credentials['expires'],
      :f_expires_at   => expires_at
    }

    # if user exists, find it and update values (but don't save now)
    # else create user
    user = User.where(:f_id => profile['id'])
    if not user.empty?
      user = user.first
      new_registered_user = (not user.email) ? true : false
      user.attributes = user_hash
    else
      new_registered_user = true
      user = User.new(user_hash)
    end

    if new_registered_user
      # Subscription to mailing list
      mimi = MadMimi.new(ENV['MADMIMI_EMAIL'], ENV['MADMIMI_KEY'])
      mimi.csv_import("email, first name, last name, full name, gender, locale\n" +
                      "#{user.email}, #{user.f_first_name}, #{user.f_last_name}, #{user.name}, #{user.gender}, #{user.locale}")
      mimi.add_to_list(user.email, ENV['MADMIMI_LIST'])

      user.update!({ :registered_at   => Time.now })
      user.update!({ :next_mailing_at => Time.now + 7.days })

      # email to admin
      UserNotifier.new_user(user.id).deliver_later

      # Post status on facebook page if %100
      if (User.registered.count+1) % 100 == 0
        FacebookFeedService.delay.publish_user_count(User.registered.count+1)
      end

      # Notify registered friends about the new user
      user.friends.registered.each do |friend|
        FacebookNotificationService.delay.notify_registered_friend(friend.id, user.id)
      end
    end

    # Facebook bug: sometimes the email is empty => investigate !
    user.email = "#{user.f_username}@facebook.com" if !user.email || user.email.empty?

    user.like_fan_page = user.request_like_fan_page?
    user.update_friends_count

    user
  end

  def first_name
    if name.nil?
      'Anonymous user' # subscribed but without any name
    else
      name.split(' ').first
    end
  end

  def registered?
    self.email != nil
  end

  def admin?
    self.f_id == ENV['FACEBOOK_ADMIN_ID'].to_i
  end

  def remove_from_application
    LevelUserLink.where(:user_id => self.id).each { |lul| lul.update(:user_id => nil) }
    PackUserLink.where(:user_id => self.id).destroy_all
    UserUserLink.where(:user_id => self.id).destroy_all
    self.destroy
  end

  # Ask facebook if this user likes the facebook fan page of the application
  # return true or false
  def request_like_fan_page?
    Rails.logger.info("TOKEN : #{self.f_token}")
    oauth = Koala::Facebook::OAuth.new(ENV['FACEBOOK_APP_ID'], ENV['FACEBOOK_APP_SECRET'])
    graph = Koala::Facebook::API.new(self.f_token)
    data  = graph.get_connections(self.f_id, "likes/#{ENV['FACEBOOK_PAGE_ID']}")

    found = false
    data.each do |like|
      found = true if like['id'] == "#{ENV['FACEBOOK_PAGE_ID']}"
    end
    return found
  end

  # If new user (no friends) or existing user and old update
  def has_to_build_friendships?
    if not self.friends_updated_at
      true
    elsif Time.now.to_date - self.friends_updated_at.to_date > DAYS_BEFORE_UPDATING_FRIENDS
      true
    else
      false
    end
  end

  # create new user for each friend and link it
  def build_friendships
    graph = Koala::Facebook::API.new(self.f_token)
    friends = graph.get_connections('me', 'friends')

    # update users and user_user_link relation
    friends.each do |friend|
      user = User.where(:f_id => friend['id']).first_or_create
      user.update!({ :name => friend['name'] })
      user.update_friends_count
      self.user_user_links.where(:user_id => self.f_id, :friend_id => user.f_id).first_or_create
    end

    # delete user_user_link is not facebook friend anymore
    friend_ids = friends.collect{ |friend| friend['id'] }
    self.user_user_links.where('user_user_links.friend_id not in (?)', friend_ids).destroy_all

    self.update!({ :friends_updated_at => Time.now })
  end

  def profile_picture(current_user_fb_graph = nil, size = "square")
    if current_user_fb_graph
      arg = (size.is_a? Integer) ? { :width => size } : { :type => size }
      current_user_fb_graph.get_picture(f_id, arg)
    else
      arg = (size.is_a? Integer) ? "width=#{size}" : "type=#{size}"
      "https://graph.facebook.com/#{self.f_id}/picture?#{arg}"
    end
  end

  # list of subscribed friends, user NOT INCLUDED, sorted by won levels (relative to one pack)
  def subscribed_friends(pack)
    friends = self.friends.registered.all
    join_users_to_pack_user_links_and_sort(friends, pack)
  end

  # list of subscribed friends, user INCLUDED, sorted by won levels (relative to one pack)
  def subscribed_friends_and_me(pack)
    friends = self.friends.registered.all + [self]
    join_users_to_pack_user_links_and_sort(friends, pack)
  end

  # n random popular friends
  # algo to maximize the selection of the people (registered or not) with a lot of registered friends
  # statisticaly we will select half the time a registered friend
  def popular_friends(n)
    registered_friends     = self.friends.registered.all
    not_registered_friends = self.friends.not_registered.order('friends_count DESC').limit(50).all
    popular_friends = []

    # array of friends of registered and not registered friends
    # [3, 55, 34, ...] means that first friend has 3 friends, second friend has 55 friends etc.
    friends_of_rf  = registered_friends.collect { |friend| friend.friends_count }
    friends_of_nrf = not_registered_friends.collect { |friend| friend.friends_count }

    # sum of the array of friends of registered and not registered friends
    # (in an array so we can later pass it by reference and get updated)
    sum_friends_of_rf  = [friends_of_rf.sum]
    sum_friends_of_nrf = [friends_of_nrf.sum]

    while popular_friends.size < n and (sum_friends_of_rf[0] != 0 or sum_friends_of_nrf[0] != 0)
      choice = rand(1..6)
      # select a registered popular friend
      if choice == 1 and sum_friends_of_rf[0] != 0
        popular_friends << select_one_user(registered_friends, friends_of_rf, sum_friends_of_rf)
      # select a not registered popular friend
      elsif choice.in? [2, 3, 4, 5, 6] and sum_friends_of_nrf[0] != 0
        popular_friends << select_one_user(not_registered_friends, friends_of_nrf, sum_friends_of_nrf)
      end
    end

    return popular_friends
  end

  def display_advertisement?
    if self.full_game
      false
    else
      Time.now >= self.send_invitations_at + DAYS_WITHOUT_ADS_IF_FRIENDS_INVITED.days.to_i
    end
  end

  def display_friends_invite_popup?
    if self.full_game
      false
    else
      Time.now >= self.send_invitations_at + DAYS_WITHOUT_FRIENDS_INVITE_POPUP.days.to_i
    end
  end

  # update friends count (friends that are on the database: registered or not)
  def update_friends_count
    # registered user or not registered user
    if self.email
      self.update!({ :friends_count => self.friends.count })
    else
      self.update!({ :friends_count => UserUserLink.where(:friend_id => self.f_id).count })
    end
  end

  def unsubscribe_from_mailing
    self.update!({ :mailing_unsubscribe => true })
    mimi = MadMimi.new(ENV['MADMIMI_EMAIL'], ENV['MADMIMI_KEY'])
    mimi.remove_from_list(self.email, ENV['MADMIMI_LIST'])
  end

  def ladder_positions
    if self.total_won_levels == 0
      { :top_friends_position => self.friends.registered.count + 1,
        :top_users_position   => User.registered.count }
    else

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_user, :only   => ['levels_to_solve', 'scores_to_improve', 'destroy']
  before_action :find_user,    :except => ['index']
  before_action :get_ladder,   :only   => ['latest_levels', 'levels_to_solve', 'scores_to_improve']
  before_action :get_friends,  :only   => ['latest_levels', 'levels_to_solve', 'scores_to_improve']

  def show
    if !current_user || current_user.id == @user.id
      # Render latest levels (no redirection because default action)
      @ladder  = get_ladder
      @friends = get_friends
      @levels  = @user.latest_levels(60)
      render 'show'
    else
      if current_user.levels_to_solve(@user).count > 0
        redirect_to levels_to_solve_user_path(@user)
      elsif current_user.scores_to_improve(@user)[:levels].count > 0
        redirect_to scores_to_improve_user_path(@user)
      else
        redirect_to latest_levels_user_path(@user)
      end
    end
  end

  def latest_levels
    @levels = @user.latest_levels(60)
    render 'show'
  end

  def levels_to_solve
    @levels = current_user.levels_to_solve(@user, 60)
    render 'show'
  end

  def scores_to_improve
    levels_and_scores = current_user.scores_to_improve(@user)
    @levels = levels_and_scores[:levels].take(60)
    @scores = levels_and_scores[:scores].take(60)
    render 'show'
  end

  def index
    @page = params[:page] ? params[:page].to_i : 1

    if current_user
      @ladder = current_user.ladder(@page)
    else
      @ladder = User.find(1).ladder(@page) # Only general datas are used
    end

    if @page == 1
      render
    else
      render :layout => false
    end
  end

  def destroy
    if current_user.id == @user.id || current_user.admin?
      @user.remove_from_application
      session[:user_id] = nil
      redirect_to '/'
    end
  end

  # HTML Templates

  def popular_friends
    @popular_friends = @user.popular_friends(6)
    render 'popular_friends', :layout => false
  end

  # JSON

  def is_like_facebook_page
    @user.like_fan_page = @user.request_like_fan_page?
    @user.save!
    render :json => { :like => @user.like_fan_page }
  end

  def update_send_invitations_at
    @user.update!({ :send_invitations_at => Time.now })
    render :json => {}
  end

  def custom_invitation
    render :json => FacebookInvitationService.popular_invitation(@user)
  end

  def unsubscribe_from_mailing
    if @user.created_at.to_i.to_s == params[:check]
      @user.unsubscribe_from_mailing
      render :plain => "We successfully unsubscribed your email (#{@user.email}) from the mailing list."
    end
  end

  protected

  def find_user
    if current_user && params[:id] == 'me'
      redirect_to user_path(current_user)
    else
      @user = User.friendly.find(params[:id])
    end
  end

  def get_ladder
    @ladder = @user.ladder
  end

  def get_friends
    @friends  = @user.friends.registered.order('total_won_levels DESC')
  end
end

app/views/users/_challenges.html.erb
<% if false && current_user %>
  <div id="challenges">
    <div id="limited-challenges">
      <h4 class="challenge-title"><%= _("Challenges") %></h4>
      <div id="invitations">
        <% unless current_user %>
          <%= link_to image_tag("facebook-connect-banner.gif"), '/connect_facebook' %>
        <% end %>
        <%# AJAX ! 'users/popular_friends' %>
      </div>
      <div id="invitations-more">
        <%= _("More users to challenge") %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_invitation.html.erb
<% link = invitation.registered? ? invitation.f_link : "http://www.facebook.com/#{invitation.f_id}" %>

<div class="invite-item" data-f_id="<%= invitation.f_id %>">
  <div class="invite-picture">
    <%= link_to image_tag(invitation.profile_picture, :title => invitation.name), link %>
  </div>
  <div class="invite-name">
    <%= link_to invitation.name, link, :title => invitation.name %>
  </div>
</div>

app/views/users/_ladder_items.html.erb
<% items.each_with_index do |user, i| %>
  <tr class="<%= 'selected' if current_user and user.id == current_user.id %>">
    <td class="num">
      <%= start+i+1 %>
    </td>
    <td class="picture">
      <%= link_to image_tag(user.profile_picture, :width => 50), user_path(user), :alt => user.name %>
    </td>
    <td class="name">
      <%= link_to user.name, user_path(user) %>
    </td>
    <td class="score">
      <%= _("<span>%{num}</span> solved levels" % { :num => user.total_won_levels }) %>
    </td>
  </tr>
<% end %>

app/views/users/index.html.erb
<% if @page == 1 %>
  <% content_for :title, _('Friends Ranking') if params[:type] == 'friends' %>
  <% content_for :title, _('Global Ranking')  if params[:type] == 'global' %>

  <% content_for :description, _("%{user_num} users solved %{level_num} levels" % { :user_num => User.registered.count, :level_num => LevelUserLink.count }) %>

  <% content_for :keywords, _('friends, ranking') if params[:type] == 'friends' %>
  <% content_for :keywords, _('global, ranking')  if params[:type] == 'global' %>

  <div id="limited-content">

    <% if current_user %>
      <% friends_selected = params[:type] == 'friends' ? 'selected friends' : '' %>
      <% global_selected  = params[:type] == 'global'  ? 'selected global' : '' %>

      <div id="ranking-buttons">
        <a class="<%= friends_selected %>" href="<%= friends_ranking_path %>"><%= _('Friends') %></a>
        <a class="<%= global_selected %>" href="<%= rankings_path %>"><%= _('Global') %></a>
      </div>

      <div style="clear:both">
      </div>
    <% end %>

    <table id="ladder">
      <% list = params[:type] == 'global' ? @ladder[:top_users] : @ladder[:top_friends] %>

      <%= render 'users/ladder_items', :items => list, :start => 0 %>
    </table>
  </div>
<% else %>
  <% list = params[:type] == 'global' ? @ladder[:top_users] : @ladder[:top_friends] %>

  <%= render 'users/ladder_items', :items => list, :start => (@page-1)*50 %>
<% end %>

app/views/users/popular_friends.html.erb
<% if current_user %>
  <%= render :partial => 'users/invitation', :collection => @popular_friends %>
<% end %>

app/views/users/show.html.erb
<div id="limited-content">
  <div id="left-side">
    <% if current_user && @user.id == current_user.id %>
      <%= link_to image_tag(@user.profile_picture(@current_user_fb_graph, 274), :class => 'profile', :alt => @user.name, :title => @user.name), user_path(@user) %>
    <% else %>
      <%= link_to image_tag(@user.profile_picture(nil, 274), :class => 'profile', :alt => @user.name, :title => @user.name), user_path(@user) %>
    <% end %>

    <table class="stats">
      <tr>
        <td class="first"><%= _('Levels solved') %></td>
        <td class="second"><%= @user.total_won_levels %></td>
      </tr>
      <tr>
        <td class="first"><%= _("Friends ranking") %></td>
        <td class="second"><%= @ladder[:top_friends_position] %> on <%= @ladder[:top_friends].count %></td>
      </tr>
      <tr>
        <td class="first"><%= _("Global ranking") %></td>
        <td class="second"><%= @ladder[:top_users_position] %> on <%= User.registered.count %></td>
      </tr>
    </table>

    <div class="friends">
      <% @friends.each do |user| %>
        <%= link_to image_tag(user.profile_picture, :width => "50"), user_path(user), :class => 'tips-users', :title => "#{user.name} - #{user.total_won_levels} levels", :alt => user.name %>
      <% end %>
    </div>

    <br/>

    <% if current_user && (@user.id == current_user.id || current_user.admin?) %>
      <div style="font-size: 12px;">
        <a href="/logout">Logout</a>
        &nbsp;|&nbsp;
        <a href="<%= user_path(@user) %>" style="color:red" data-confirm="Are you sure to destroy your account? All your solved levels will also be deleted. This operation will not be reversible." data-method="delete">Destroy my account</a>
      </div>
    <% end %>

    <% if Rails.env.development? %>
      <br/>
      <a href="?force_user_slug=<%= @user.slug %>">Impersonation</a>
    <% end %>
  </div>

  <div id="right-side">
    <div id="tabs">
      <% solve_active   = params[:action] == 'levels_to_solve'   ? 'active' : '' %>
      <% improve_active = params[:action] == 'scores_to_improve' ? 'active' : '' %>
      <% latest_active  = params[:action] == 'latest_levels'     ? 'active' : '' %>
      <% if current_user and current_user.id != @user.id %>
        <% u_u = UserUserLink.find_by_user_id_and_friend_id(current_user.f_id, @user.f_id) %>

        <div class="tab tips-top <%= solve_active %>" title="<%= _("Levels %{username} solved and not me" % { :username => @user.first_name }) %>">
          <%= link_to _("%{username} > Me" % { :username => @user.first_name }), levels_to_solve_user_path(@user) %>
          <% if u_u and (count = u_u.levels_to_solve_count) > 0 %>
            <div class="number">
              <%= count %>
            </div>
          <% end %>
        </div>
        <div class="tab tips-top <%= improve_active %>" title="<%= _("Levels where %{username} did a better score than me" % { :username => @user.first_name }) %>">
          <%= link_to _("%{username} ~ Me" % { :username => @user.first_name }), scores_to_improve_user_path(@user) %>
          <% if u_u and (count = u_u.scores_to_improve_count) > 0 %>
            <div class="number">
              <%= UserUserLink.find_by_user_id_and_friend_id(current_user.f_id, @user.f_id).scores_to_improve_count %>
            </div>
          <% end %>
        </div>
      <% end %>
      <div class="tab tips-top <%= latest_active %>" title="<%= _("Latest levels solved by %{username}" % { :username => @user.first_name }) %>">
        <%= link_to _('Latests'), latest_levels_user_path(@user) %>
      </div>
      <div style="clear:both"></div>
    </div>

    <% @levels.each do |level| %>
      <a href="<%= pack_level_path(level.pack, level) %>">
        <div class="level level-<%= level.id %> tips-levels" title="<%= level.name %>" <%= level_datas(level) %>>
          <div id="level-<%= level.id %>-canvas">
          </div>
        </div>
      </a>
    <% end %>

    <% if @levels.empty? %>
      <div class="empty-list">
        <%= _('No levels in this category') %>
      </div>
    <% end %>
  </div>

  <div style="clear:both">
  </div>
</div>