config/routes.rb
Rails.application.routes.draw do
  resources :packs do
    resources :levels

    member do
      get :download
    end
  end

  resources :workflows do
    collection do
      get :show_welcome
      get :show_rules
      get :show_controls

      get :show_facebook_page
      get :show_twitter_page
      get :show_invite_friends
      get :show_random_level
      get :show_donation

      post :show_next_level
    end
  end

  resources :scores

  resources :users do
    member do
      get  :popular_friends
      get  :is_like_facebook_page      # question
      get  :custom_invitation          # JSON with data for custom user invitation
      post :update_send_invitations_at # user just invited some friends
      get  :unsubscribe_from_mailing   # remove user from mailing list (remove from madmimi)

      get  :latest_levels
      get  :levels_to_solve
      get  :scores_to_improve
    end
  end

  # API

  namespace :api do
    resources :levels do
      collection do
        get :random
      end
    end
  end

  get '/rankings',        :to => 'users#index', :type => 'global',  :as => :rankings
  get '/friends_ranking', :to => 'users#index', :type => 'friends', :as => :friends_ranking

  # Root
  root :to => "packs#show", :id => 'dimitri-yorick' # or 'Novoban'
  post "/" => "packs#show", :id => 'dimitri-yorick'

  # Redirect user back to the page before login
  # http://forrst.com/posts/Redirect_a_user_back_to_the_current_page_after_a-R1q
  get '/connect_facebook',          :to => 'sessions#connect_facebook'

  # OmniAuth (facebook)
  match '/auth/:provider/callback', :to => 'sessions#create',  via: [:get, :post]
  match '/auth/failure',            :to => 'sessions#failure', via: [:get, :post]
  get   '/login',                   :to => 'sessions#new'
  get   '/logout',                  :to => 'sessions#destroy', :as => :logout

  get   '/banner',                  :to => 'pages#banner'
  get   '/privacy_policy',          :to => 'pages#privacy_policy'
  get   '/terms_of_service',        :to => 'pages#terms_of_service'
  get   '/stats',                   :to => 'pages#stats'
  get   '/master_thesis',           :to => 'pages#master_thesis'
end

app/models/pack.rb
class Pack < ApplicationRecord
  extend FriendlyId

  friendly_id :name, :use => :slugged

  # Associations
  has_many :levels
  has_many :pack_user_links
  has_many :users,           :through => :pack_user_links

  # Scope
  default_scope { order('name ASC') }

  # Nested attributes

  # Validations

  # Callbacks

  # Class Methods

  def self.won_level_ids(current_user)
    current_user ? current_user.scores.pluck(:level_id).uniq : []
  end

  def self.won_levels_list(current_user)
    won_level_ids(current_user).join(',')
  end

  # Methods

  def won_level_ids(current_user)
    current_user ? current_user.scores.where(:level_id => self.levels).pluck(:level_id).uniq : []
  end

  def won_levels_list(current_user)
    won_level_ids(current_user).join(',')
  end
end

app/controllers/packs_controller.rb
class PacksController < ApplicationController
  def index
    @packs = Pack.all
  end

  def show
    @pack = Pack.friendly.find(params[:id])
    @level = @pack.levels.first

    # Take first two rows of friends and public scores
    # (other rows are displayed by scores_controller in AJAX)
    @pushes_scores         = @level.best_global_scores(current_user, 6)
    @pushes_scores_friends = @level.best_friends_scores(current_user, 6)
  end

  def download
    @pack = Pack.friendly.find(params[:id])
    send_file "lib/assets/levels/#{@pack.file_name}.slc",
              :type => 'text/xml'
  end
end

app/views/packs/_invitations.html.erb
<% if current_user %>
  <%= render :partial => 'users/invitation', :collection => current_user.popular_friends(5) %>
  <div id="invitations-more">
    More challenges
  </div>
<% else %>
  <%# link_to image_tag("facebook-connect-banner.gif"), '/auth/facebook' %>
<% end %>

app/views/packs/_show_deadlock_message.html.erb
<div id="deadlock">
  <div id="deadlock-message">
    <%= _('A <a class="tips" href="http://www.sokobano.de/wiki/index.php?title=Deadlocks" title="Click for more informations about Sokoban deadlocks">deadlock</a> has been found') %>
  </div>
  <div id="deadlock-press-d">
    <span><%= _('Press %{d} to cancel the last move' % { :d => image_tag("key_d.png") }) %></span>
  </div>
</div>

app/views/packs/_show_game.html.erb
<div id="game">
  <%= render 'packs/show_deadlock_message' %>
  <div class="fullscreen">
  </div>
  <div class="game-out">
    <div id="raphael" class="game-in">&nbsp;</div>
  </div>
  <div class="large-shad">&nbsp;</div>

  <div id="current-score" class="score">
    <div class="score-pushes">0</div>
    <div class="score-pushes-text"><%= _('pushes') %></div>
    <div class="score-moves">0</div>
    <div class="score-moves-text"><%= _('moves') %></div>
  </div>
</div>

app/views/packs/_show_webgl_canvas.html.erb
<canvas id="webgl" width="730" height="470">
  <%= _("Sorry, your browser doesn't support the &lt;canvas/&gt; tag. Please come back with a newer browser.") %>
</canvas>

app/views/packs/index.html.erb
<div id="limited-content">

  <% @packs.each do |pack| %>
    <h2 style="font-weight:bold;display:inline"><%= pack.name %></h2>  / <%= pack.levels_count %> levels

    <div style="margin-top:10px;margin-bottom:30px">
      <table>
        <tr>
          <td><%= _("Filename") %></td>
          <td style="padding-left:10px;padding-right:10px">:</td>
          <td><%= link_to "#{pack.file_name}.slc", download_pack_path(pack) %></td>
        </tr>
        <tr>
          <td><%= _("Description") %></td>
          <td style="padding-left:10px;padding-right:10px">:</td>
          <td><%= pack.description %></td>
        </tr>
        <tr>
          <td><%= _("Email") %></td>
          <td style="padding-left:10px;padding-right:10px">:</td>
          <td><%= pack.email %></td>
        </tr>
        <tr>
          <td><%= _("Url") %></td>
          <td style="padding-left:10px;padding-right:10px">:</td>
          <td><a href="<%= pack.url %>"><%= pack.url %></a></td>
        </tr>
        <tr>
          <td><%= _("Copyright") %></td>
          <td style="padding-left:10px;padding-right:10px">:</td>
          <td><%= pack.copyright %></td>
        </tr>
      </table>
    </div>
  <% end %>
</div>

app/views/packs/show.html.erb
<div id="limited-content">

  <%# render 'layouts/advert_body' %>

  <div id="menu-levels">
    <div id="current-level-name" itemscope itemtype="http://schema.org/Thing">
      <a href="<%= pack_level_url(@pack, @level) %>" itemprop="url">
        <h2 itemprop="name"><%= @level.name %></h2>
      </a>
    </div>
    <img id="current-level-image" itemprop="image" src="<%= @level.thumb %>"/>

    <div id="packs" data-pack-slug="<%= @pack.slug %>"
                    data-pack-name="<%= @pack.name %>"
                    data-pack-id="<%= @pack.id %>">
      <select>
        <% pack_user_links = current_user ? PackUserLink.where(:user_id => current_user.id).all : [] %>
        <% Pack.all.each do |pack| %>
          <% pack_user_link     = pack_user_links.select { |p_u| p_u.pack_id == pack.id } %>
          <% pack_success_count = pack_user_link.empty? ? 0 : pack_user_link.first.won_levels_count %>
          <% pack_levels_count  = pack.levels_count %>
          <% pack_success       = "[#{pack_success_count}/#{pack_levels_count}]" %>
          <option value="<%= pack.slug %>" <%= 'selected=selected' if pack.id == @pack.id %>><%= pack.name %> <%= pack_success %></option>
        <% end %>
      </select>

      <div class="packs-button">
        <a class="tips" title="<%= _("Can you solve this level?") %>" href="#"><%= _("Challenge") %></a>
      </div>
      <div class="clear">&nbsp;</div>
    </div>

    <% cache @pack do %>
      <ul id="levels" class="levels">
        <% @pack.levels.each_with_index do |level, index| %>
          <li id="level-<%= level.id %>" <%= level_datas(level) %>>
            <a href="<%= pack_level_path(@pack, level) %>" title="<%= level.name %>">
              <span class="star s-icon-star-empty"></span>
              <span class="level-index"><%= index+1 %></span>
            </a>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="level-thumb" data-level-grid="" data-level-width="" data-level-height="">
    <div class="level-thumb-in">
      <div id="level-thumb-canvas"></div>
    </div>
  </div>

  <%= render 'packs/show_game' %>
</div>

<div id="limited-content-xl">
  <%# render 'users/challenges' %>

  <div id="scores">
    <%= render 'level_user_links/index' %>
  </div>
</div>