config/routes.rb
Rails.application.routes.draw do
  resources :packs do
    resources :levels

    member do
      get :download
    end
  end

  resources :workflows do
    collection do
      get :show_welcome
      get :show_rules
      get :show_controls

      get :show_facebook_page
      get :show_twitter_page
      get :show_invite_friends
      get :show_random_level
      get :show_donation

      post :show_next_level
    end
  end

  resources :scores

  resources :users do
    member do
      get  :popular_friends
      get  :is_like_facebook_page      # question
      get  :custom_invitation          # JSON with data for custom user invitation
      post :update_send_invitations_at # user just invited some friends
      get  :unsubscribe_from_mailing   # remove user from mailing list (remove from madmimi)

      get  :latest_levels
      get  :levels_to_solve
      get  :scores_to_improve
    end
  end

  # API

  namespace :api do
    resources :levels do
      collection do
        get :random
      end
    end
  end

  get '/rankings',        :to => 'users#index', :type => 'global',  :as => :rankings
  get '/friends_ranking', :to => 'users#index', :type => 'friends', :as => :friends_ranking

  # Root
  root :to => "packs#show", :id => 'dimitri-yorick' # or 'Novoban'
  post "/" => "packs#show", :id => 'dimitri-yorick'

  # Redirect user back to the page before login
  # http://forrst.com/posts/Redirect_a_user_back_to_the_current_page_after_a-R1q
  get '/connect_facebook',          :to => 'sessions#connect_facebook'

  # OmniAuth (facebook)
  match '/auth/:provider/callback', :to => 'sessions#create',  via: [:get, :post]
  match '/auth/failure',            :to => 'sessions#failure', via: [:get, :post]
  get   '/login',                   :to => 'sessions#new'
  get   '/logout',                  :to => 'sessions#destroy', :as => :logout

  get   '/banner',                  :to => 'pages#banner'
  get   '/privacy_policy',          :to => 'pages#privacy_policy'
  get   '/terms_of_service',        :to => 'pages#terms_of_service'
  get   '/stats',                   :to => 'pages#stats'
  get   '/master_thesis',           :to => 'pages#master_thesis'
end

app/views/layouts/_advert_body_adsense.html.erb
<script type="text/javascript"><!--
  google_ad_client = "ca-pub-8021968418597007";
  /* bannière */
  google_ad_slot = "7066689098";
  google_ad_width = 728;
  google_ad_height = 90;
  //-->
</script>
<script type="text/javascript" src="//pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

app/views/layouts/_advert_body_lifestreetmedia.html.erb
<% if current_user and current_user.gender == 'male' %>
  <% adkey = 'aa3' %>
  <% slot  = 'slot71897' %>
<% elsif current_user and current_user.gender == 'female' %>
  <% adkey = 'd27' %>
  <% slot  = 'slot71898' %>
<% else %>
  <% adkey = 'b87' %>
  <% slot  = 'slot71899' %>
<% end %>

<script type="text/javascript">
  //<![CDATA[
    if(!(typeof LSM_Slot == 'undefined')) {
      LSM_Slot({
        adkey: '<%= adkey %>',
        ad_size: '728x90',
        slot: '<%= slot %>'
      });
    };
  //]]>
</script>

app/views/layouts/_advert_head.html.erb
<script src="//ads.lfstmedia.com/getad?site=154078" type="text/javascript"></script>

app/views/layouts/_advert_headers.html.erb
<script src="//ads.lfstmedia.com/getad?site=154078" type="text/javascript"></script>

app/views/layouts/_banner.html.erb
<% if params[:controller] == 'users' && params[:action] == 'index' %>

  <% banner_class = 'banner-text' %>

  <% if !current_user %>
    <% text = _("Global Ranking : %{user_num} users solved %{level_num} levels" % { :user_num => User.registered.count, :level_num => LevelUserLink.count }) %>
  <% else %>
    <% if params[:type] == 'global' %>
      <% text = _("Global Ranking") + ' : ' +  @ladder[:top_users_position].to_s + ' / ' + User.registered.count.to_s %>
    <% else %>
      <% text = _("Friends Ranking") + ' : ' + @ladder[:top_friends_position].to_s + ' / ' + @ladder[:top_friends].count.to_s %>
    <% end %>
  <% end %>

<% elsif params[:controller] == 'users' && params[:action].in?(%w(show latest_levels levels_to_solve scores_to_improve)) %>

  <% banner_class = 'banner-text' %>
  <% text = @user.name %>

<% elsif params[:controller] == 'packs' && params[:action] == 'index' %>

  <% banner_class = 'banner-text' %>
  <% text = _("List of Packs & Copyright") %>

<% elsif !current_user && !@pack %>

  <% banner_class = 'banner-text' %>
  <% text = _("Play Sokoban and Challenge your Friends") %>

<% elsif !current_user && @pack %>

  <% banner_class = 'banner-text' %>
  <% text = @pack.name %>

<% else %>

  <% banner_class = 'banner-friends' %>

<% end %>


<div id="banner" class="<%= banner_class %>">
  <div id="limited-banner">
    <% if banner_class == 'banner-text' %>

      <h1><%= text %></h1>

      <% if @pack %>
        <div id="current-level-description" itemprop="description">
          <%= "#{@pack.description} (#{@pack.copyright})" %>
        </div>
      <% end %>

    <% elsif banner_class == 'banner-friends' %>

      <%# was only useful for fb app requests %>
      <%# render 'layouts/fb_friend_ids' %>

      <ul id="users-top">
        <% if @pack %>
          <% subscribed_friends_and_me = current_user.subscribed_friends_and_me(@pack).take(16) %>
          <% u_u_links = UserUserLink.where(:user_id => current_user.f_id, :friend_id => subscribed_friends_and_me.collect(&:f_id)) %>
          <% array_counts = u_u_links.collect { |u_u| [ u_u.friend_id, u_u.total_improve_count ] }.flatten %>
          <% hash_counts  = Hash[*array_counts] %>

          <% subscribed_friends_and_me.each do |friend| %>
            <li>
              <a href="<%= user_path(friend) %>">
                <%= image_tag friend.profile_picture(@current_user_fb_graph), 'data-f_id' => friend.f_id, :class => 'facebook-friends' %>

                <span style="display:none" data-user-id="<%= friend['user_id'] ? friend.user_id : friend.id %>"
                                           data-user-name="<%= friend.name %>"
                                           data-user-gender="<%= friend.gender %>"
                                           data-local-success="<%= friend['won_levels_count'] ? friend.won_levels_count : 0 %>"
                                           data-global-success="<%= friend.total_won_levels %>">
                  <% # won levels ids of current pack OR every won levels id %>
                  <%= friend['won_levels_list'] ? friend.won_levels_list : '' %>
                </span>
              </a>
              <% if current_user.f_id != friend.f_id and hash_counts[friend.f_id] > 0 %>
                <div class="number">
                  <%= hash_counts[friend.f_id] %>
                </div>
              <% end %>
            </li>
          <% end %>
        <% end %>

<!--         <li>
          <a href="#">
            <%= image_tag 'add_friend.png', :id => 'add-one-friend', :class => 'tips popup', :title => _('Challenge one friend on this level') %>
          </a>
        </li> -->

        <li>
          <a href="#">
            <%= image_tag 'add_friends.png', :id => 'add-more-friends', :class => 'tips popup', :title => _('Invite more friends') %>
          </a>
        </li>

        <li>
          <a href="#">
            <%= image_tag 'add_wall.png', :id => 'share-on-wall', :class => 'tips popup', :title => _('Share the current level on your Facebook feed') %>
          </a>
        </li>
      </ul>

    <% end %>
  </div>
</div>

<% if banner_class == 'banner-friends' %>
  <div id="user-hover">
    <div class="user-hover-in">
      <div class="user-name">...</div>
      <div class="user-stars">
        <div class="user-stars-pack">
          <span class="star icon-star"></span>
          <span class="num">...</span>
          <span><%= _("In this pack") %></span>
        </div>
        <div class="user-stars-total">
          <span class="star icon-star"></span>
          <span class="num">...</span>
          <span><%= _("Total") %></span>
        </div>
      </div>
      <div class="user-challenge-this">
        <%= link_to _("CLICK TO SEE HIS SCORES"), '#', 'data-male'   => _("CLICK TO SEE HIS SCORES"),
                                                       'data-female' => _("CLICK TO SEE HER SCORES") %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_delayed_javascript.html.erb
<script type="text/javascript">
 // Add a script element as a child of the body
 function downloadJSAtOnload() {
   var element = document.createElement("script");
   element.src = "<%= javascript_path 'application' %>";
   document.body.appendChild(element);
 }

 // Check for browser support of event handling capability
 if (window.addEventListener)
   window.addEventListener("load", downloadJSAtOnload, false);
 else if (window.attachEvent)
   window.attachEvent("onload", downloadJSAtOnload);
 else
  window.onload = downloadJSAtOnload;
</script>

app/views/layouts/_facebook_headers.html.erb
<div id="fb-root"></div>

<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_footer.html.erb
<%= link_to _("Terms of Service"), '/terms_of_service' %>
|
<%= link_to _("Privacy Policy"), '/privacy_policy' %>
|
<%= link_to _("Packs Copyright"), '/packs' %>
|
<% if current_user and current_user.admin? %>
  <%= link_to _("Stats"), '/stats' %>
  |
<% end %>
<%= link_to _("Contact us"), 'mailto:contact@sokoban-game.com' %>

app/views/layouts/_github_banner.html.erb
<a id="github-banner" href="https://github.com/MichaelHoste/sokoban">
  <i class="icon-large icon-github"></i>&nbsp;&nbsp;<%= _("Fork me on GitHub") %>
</a>

app/views/layouts/_google_analytics_headers.html.erb
<% if Rails.env.production? %>
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-32487253-1']);
    _gaq.push(['_setDomainName', 'sokoban-game.com']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
<% end %>

app/views/layouts/_googleplus_headers.html.erb
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>

app/views/layouts/_header.html.erb
<header class="header">
  <div id="limited-header">

    <div id="title">
      <%= link_to 'Sokoban', :root %>
      <div>Free and Social Puzzle Game</div>
    </div>

    <div id="menus" data-level-id="<%= @level.id if @level %>">
      <ul>
        <% if not current_user %>
          <li class="ranking-menu">
            <div>
              <%= link_to _('Rankings'), rankings_path %>
            </div>
          </li>
        <% end %>

        <% if current_user %>
          <li class="name fb_logged" id="user-infos" data-id="<%= current_user.id %>"
                                                     data-global-success="<%= current_user.total_won_levels %>"
                                                     data-like-facebook-page="<%= current_user.like_fan_page %>"
                                                     data-registered-friends="<%= current_user.friends.registered.count %>"
                                                     data-display-invite-popup="<%= current_user.display_friends_invite_popup? %>"
                                                     data-won-levels-list="<%= PackUserLink.find_by_pack_id_and_user_id(@pack.id, current_user.id).try(:won_levels_list) if @pack %>">
            <div>
              <a class="fb_img" href="<%= user_path(current_user) %>">
                <%= image_tag current_user.profile_picture(@current_user_fb_graph), :title => current_user.name %>
              </a>
              <a href="<%= user_path(current_user) %>"><%= current_user.name %></a>
            </div>
          </li>
        <% else %>
          <li class="name fb-login">
            <div>
              <a href="/connect_facebook"><%= _('Login with Facebook') %></a>
            </div>
          </li>
        <% end %>

        <!---
        <li class="challenges-menu"><i class="icon-trophy"></i>&nbsp;Challenges</li>
        <li class="packs-menu is-selected"><i class="icon-star"></i>&nbsp;Packs</li>
        -->

        <% if current_user %>
          <li class="ranking-position">
            <div>
              <% @ladder_positions = current_user.ladder_positions %>
              <%= link_to "#{@ladder_positions[:top_users_position]} / #{User.registered.count}", rankings_path %>
            </div>
          </li>
        <% end %>

        <li class="rules-menu">
          <div><%= _("Rules") %></div>
        </li>
      </ul>
    </div>

    <% if not current_user %>
      <div id="likes">
        <div class="fb-like" data-href="https://www.facebook.com/sokoban.game" data-width="450" data-layout="button_count" data-show-faces="false" data-send="false"></div>

        <!--

        <div class='twitter-like'>
          <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://sokoban-game.com" data-text="Come and Play this Sokoban Game with Me !" data-hashtags="sokoban">Tweet</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        </div>

        <div class="gplus-like">
          <div class="g-plusone" data-size="medium" data-href="http://sokoban-game.com"></div>
        </div>

        -->
      </div>
    <% end %>

  </div>
</header>

app/views/layouts/privacy_policy.html.erb
<div style="width: 800px;left: -400px;margin-left:50%;position:relative;margin-top: 20px;margin-bottom: 20px;">

  <h1>Privacy Policy</h1>

  <p>
    80LIMIT SRL ("us", "we", or "our"), company registered at Avenue de l'Hôpital 77, 7000 Mons, Belgium, CBE Number / VAT: BE0846734972 - RPM Mons, operates the <a href="https://sokoban-game.com" target="_blank">sokoban-game.com</a> website (the "Service").
  </p>

  <p>
    This privacy policy will explain how our organization uses the personal data we collect from you when you use our website.
  </p>

  <p>
    Topics:
  </p>

  <ul>
    <li>What data do we collect?</li>
    <li>How do we collect your data?</li>
    <li>How will we use your data?</li>
    <li>How do we store your data?</li>
    <li>Marketing</li>
    <li>What are your data protection rights?</li>
    <li>What are cookies?</li>
    <li>How do we use cookies?</li>
    <li>What types of cookies do we use?</li>
    <li>How to manage your cookies</li>
    <li>Privacy policies of other websites</li>
    <li>Changes to our privacy policy</li>
    <li>How to contact us</li>
    <li>How to contact the appropriate authorities</li>
  </ul>


  <h2>
    What data do we collect?
  </h2>

  <p>
    We collect the following data:
  </p>

  <ul>
    <li>
      Personal identification information:
      <ul>
        <li>Name.</li>
        <li>Facebook ID number.</li>
        <li>Email address (only when Facebook shares it).</li>
      </ul>
    </li>
  </ul>

  <h2>
    How do we collect your data?
  </h2>

  <p>
    You directly provide us with most of the data we collect.
  </p>

  <p>
    We collect data and process data when you:
  </p>

  <ul>
    <li>
      Register online using the “connect with Facebook” button.
    </li>
  </ul>

  <h2>
    How will we use your data?
  </h2>

  <p>
    We collecte your data so that we can:
  </p>

  <ul>
    <li>Save your personal Sokoban scores on your account.</li>
    <li>Email you with required transactional emails (lost password).</li>
    <li>Email you with optional transactional emails (a friend beat your score)</li>
  </ul>

  <h2>
    How do we store your data?
  </h2>

  <p>
    We securely store your data on a database at a Scaleway datacenter (https://scaleway.com)
  </p>

  <h2>
    Marketing
  </h2>

  <p>
    We don’t share your data for any marketing purposes.
  </p>

  <h2>
    What are your data protection rights?
  </h2>

  <p>
    We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:
  </p>

  <p>
    <strong>The right to access</strong> – You have the right to request us for copies of your personal data. We may charge you a small fee for this service.
  </p>

  <p>
    <strong>The right to rectification</strong> – You have the right to request that we correct any information you believe is inaccurate. You also have the right to request us to complete the information you believe is incomplete.
  </p>

  <p>
    <strong>The right to erasure</strong> – You have the right to request that we erase your personal data. You can trigger this automated and irreversible action on your personal page. You can access it by clicking on your name. The link is named “Destroy my account” and is visible on the bottom left.
  </p>

  <p>
    <strong>The right to restrict processing</strong> – You have the right to request that we restrict the processing of your personal data, under certain conditions.
  </p>

  <p>
    <strong>The right to object to processing</strong> – You have the right to object to our processing of your personal data, under certain conditions.
  </p>

  <p>
    <strong>The right to data portability</strong> – You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.
  </p>

  <p>
    If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us at our email: <a href="mailto:contact@sokoban-game.com" target="_blank">contact@sokoban-game.com</a>
  </p>

  <h2>
    Cookies
  </h2>

  <p>
    Cookies are text files placed on your computer to collect standard Internet log information and visitor behavior information. When you visit our websites, we may collect information from you automatically through cookies or similar technology
  </p>

  <p>
    For further information, visit <a href="https://allaboutcookies.org" target="_blank">allaboutcookies.org</a>.
  </p>

  <h2>
    How do we use cookies?
  </h2>

  <p>
  we use cookies in a range of ways to improve your experience on our website, including:
  </p>

  <ul>
    <li>Keeping you signed in</li>
    <li>Understanding how you use our website</li>
  </ul>

  <h2>
    What types of cookies do we use?
  </h2>


  <p>
    There are a number of different types of cookies, however, our website uses:
  </p>

  <ul>
    <li><strong>Functionality</strong> – We use these cookies so that we recognize you on our website and remember your previously selected preferences. These could include what language you prefer and location you are in. A mix of first-party and third-party cookies are used.</li>
    <li><strong>Debugging</strong> – We use these cookies to collect information about the errors that are triggered on your browser when using the website, in order to fix them later.</li>
    <li><strong>Analytics</strong> – We use these cookies to better understand the popularity and usage of our website.</li>
  </ul>

  <h2>
    How to manage cookies
  </h2>

  <p>
    You can set your browser not to accept cookies, and the above website tells you how to remove cookies from your browser. However, in a few cases, some of our website features may not function as a result.
  </p>

  <h2>
    Privacy policies of other websites
  </h2>

  <p>
    The <a href="https://sokoban-game.com" target="_blank">sokoban-game.com</a> website contains links to other websites. Our privacy policy applies only to our website, so if you click on a link to another website, you should read their privacy policy.
  </p>

  <h2>
    Changes to our privacy policy
  </h2>

  <p>
    We keep its privacy policy under regular review and places any updates on this web page. This privacy policy was last updated on 1st september 2021.
  </p>

  <h2>
    How to contact us
  </h2>

  <p>
    If you have any questions about our privacy policy, the data we hold on you, or you would like to exercise one of your data protection rights, please do not hesitate to contact us.
  </p>

  <p>
    Email us at: <a href="mailto:contact@sokoban-game.com" target="_blank">contact@sokoban-game.com</a>
  </p>

  <%= link_to "Back to Sokoban", root_path %>
















  <!--

  <h1>
  	Privacy Policy
  </h1>

  <p>
  	Your privacy is very important to us. Accordingly, we have developed this
  	Policy in order for you to understand how we collect, use, communicate and
  	disclose and make use of personal information. The following outlines our
  	privacy policy.
  </p>

  <ul>
  	<li>
  		Before or at the time of collecting personal information, we will identify
  		the purposes for which information is being collected.
  	</li>
  	<li>
  		We will collect and use of personal information solely with the objective
  		of fulfilling those purposes specified by us and for other compatible
  		purposes, unless we obtain the consent of the individual concerned or as
  		required by law.
  	</li>
  	<li>
  		We will only retain personal information as long as necessary for the
  		fulfillment of those purposes.
  	</li>
  	<li>
  		We will collect personal information by lawful and fair means and, where
  		appropriate, with the knowledge or consent of the individual concerned.
  	</li>
  	<li>
  		Personal data should be relevant to the purposes for which it is to be used,
  		and, to the extent necessary for those purposes, should be accurate, complete,
  		and up-to-date.
  	</li>
  	<li>
  		We will protect personal information by reasonable security safeguards against
  		loss or theft, as well as unauthorized access, disclosure, copying, use or
  		modification.
  	</li>
  	<li>
  		We will make readily available to customers information about our policies and
  		practices relating to the management of personal information.
  	</li>
  </ul>

  <p>
  	We are committed to conducting our business in accordance with these principles
  	in order to ensure that the confidentiality of personal information is protected
  	and maintained.
  </p>

   -->
</div>

app/views/layouts/stats.html.erb
<html>
<body>

<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

<div id="limited-content">
  <strong>Users</strong> : <%= @total_users %> (<%= @total_friends %> amis)

  <% data = User.registered.where('registered_at > ?', Time.new(2013, 3))
                           .group_by_month(:registered_at).count %>
  <% end_date = data.keys.last %>
  <% extrapolation = (Time.now.utc - end_date) / 1.month.to_i %>
  <% data[data.keys.last] /= extrapolation %>
  <%= line_chart data %>

  <br/><br/>

  <strong>Completed Levels</strong> : <%= @best_scores %> / <%= @total_scores %>

  <% data =  LevelUserLink.where('created_at > ?', Time.new(2013, 3))
                           .group_by_month(:created_at).count %>
  <% end_date = data.keys.last %>
  <% extrapolation = (Time.now.utc - end_date) / 1.month.to_i %>
  <% data[data.keys.last] /= extrapolation %>
  <%= line_chart data %>

  <br/>

  <strong>Total completed Levels</strong> : <%= @total_scores %>

  <% data = {} %>
  <% time = Time.new(2013, 1).to_datetime %>
  <% total = 0 %>
  <% while time < Time.now + 1.month %>
    <% total += LevelUserLink.where('created_at > ? AND created_at <= ?', time - 1.month, time).count %>
    <% data.merge!({ time => total }) %>
    <% time = time + 1.month %>
  <% end %>

  <%= line_chart data %>

  <br/>

  <strong>Total users</strong> : <%= @total_users %>

  <% data = {} %>
  <% time = Time.new(2013, 1).to_datetime %>
  <% total = 0 %>
  <% while time < Time.now + 1.month %>
    <% total += User.registered.where('registered_at > ? AND registered_at <= ?', time - 1.month, time).count %>
    <% data.merge!({ time => total }) %>
    <% time = time + 1.month %>
  <% end %>

  <%= line_chart data %>

  <br/>

  <strong>Distribution of number of solved levels</strong>

  <%= column_chart @distribution %>

  <strong>Tasks</strong>

  <ul>
    <% @jobs.each do |job| %>
      <li><%= "#{job.attempts} attempts - #{job.queue} - last error : #{job.last_error}" %></li>
    <% end %>
    <li><%= @pending_mails %> pending mails</li>
    <li><%= @mails_by_week %> mails per week</li>
  </ul>

  <br/>

  <strong>Last 20 users</strong> :

  <div>
    <% @last_users.each do |user| %>
      <div>
        <%= link_to image_tag(user.profile_picture, :width => '25px', :class => 'tips', :title => "#{user.name} - #{user.total_won_levels}"), user_path(user) %>
        |
        <%= user.name %>
        |
        <%= when_in_the_past(user.registered_at) %>
        |
        <%= user.total_won_levels %> completed levels
      </div>
    <% end %>
  </div>

  <br/><br/>

  <strong>Last 100 completed levels</strong> :

  <div>
    <% @last_scores.each do |score| %>
      <% user_picture = (score.user_id ? score.user.profile_picture : 'default_user.gif' )%>
      <% user_link = (score.user_id ? user_path(score.user) : '#') %>
      <% won_levels = score.user ? score.user.total_won_levels : 0 %>

      <div>
        <%= link_to image_tag(user_picture, :width => '25px', :class => 'tips', :title => "#{score.user_name} - #{won_levels}"), user_link %>
        |
        <%= score.user_name %>
        |
        <%= when_in_the_past(score.created_at) %>
        |
        <%= link_to "#{score.level.pack.name} / #{score.level.name}", pack_level_path(score.level.pack, score.level) %>
      </div>
    <% end %>
  </div>

  <br/><br/>
</div>
</body>
</html>